spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
    open-in-view: on
decorator:
  datasource:
    # p6spy 설정 적용
    p6spy:
      enable-logging: true

#      multiline: true
#      logging: slf4j

